'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8806
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PharmRetail.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adddatabase_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adddatabase_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addfile_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addfile_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addusermale_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addusermale_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowright_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowright_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property automation_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("automation_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blackberry_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackberry_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashinhand_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashinhand_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cashinhand_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cashinhand_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cellphone_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cellphone_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changeuser_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changeuser_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheap2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheap2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cheap2filled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheap2filled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkbook_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbook_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkbook_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkbook_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkmark_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checkmark_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comments_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comments_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property commodity_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("commodity_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property company_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conferencefilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conferencefilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conferencefilled_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conferencefilled_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property contactus_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contactus_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property create_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("create_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cribfilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cribfilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property currencyexchange_024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("currencyexchange_024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property currencyexchange_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("currencyexchange_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property currencyexchange_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("currencyexchange_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property databaseadministrator_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("databaseadministrator_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property databaseview_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("databaseview_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property databaseviewfilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("databaseviewfilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dataquality_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dataquality_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dataquality_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dataquality_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dateto_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dateto_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deleteticket_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deleteticket_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorhanger_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorhanger_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorhanger_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorhanger_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property downloads_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downloads_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dupcopy_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dupcopy_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exchange_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exchange_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exchange_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exchange_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exitdp_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitdp_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exportpdf_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportpdf_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property femalespeaker_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("femalespeaker_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property file_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filter_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filterfilled_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filterfilled_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flow_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flow_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property flow_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flow_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folderfilledb_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folderfilledb_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property generalledger_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("generalledger_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property handshake_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("handshake_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property handshake_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("handshake_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property handshakec_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("handshakec_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property hashtag_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hashtag_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hashtag_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hashtag_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property homepage_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homepage_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property increase_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("increase_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property information_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property insertcard_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insertcard_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property insertcard_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insertcard_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoice_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jogforward_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jogforward_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_filled_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linkdocument_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linkdocument_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linkdocument_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linkdocument_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property livefolder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("livefolder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property meetingroom_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("meetingroom_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moneybag_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moneybag_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property opendoor_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("opendoor_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolderf_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolderf_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property openedfolderfilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openedfolderfilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property organization_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("organization_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paid_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paid_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paid_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paid_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property papermoney_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("papermoney_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people_24g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people_24g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property percentage_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("percentage_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plusmath_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plusmath_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property postcard_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postcard_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property processor_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("processor_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property productdocumentsfilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("productdocumentsfilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property read_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("read_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property registryeditor_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("registryeditor_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property returnpurchase_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("returnpurchase_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savetabslist_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savetabslist_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property schedule_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("schedule_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scrollup_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scrollup_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property searchfilled_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searchfilled_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property searchfilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searchfilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property securitylock_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("securitylock_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property securitylock_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("securitylock_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property services_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("services_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settings_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shoppingcart_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoppingcart_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smartcard_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smartcard_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smartcard_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smartcard_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property socceryellowcard_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("socceryellowcard_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sortbymodifieddate_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortbymodifieddate_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symlinkfile_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symlinkfile_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property synchronize_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("synchronize_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property today_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("today_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property triangle_arrow_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triangle_arrow_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unavailable_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unavailable_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unavailable_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unavailable_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uploadftp_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uploadftp_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property uploadtothecloud_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uploadtothecloud_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermalefilled_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermalefilled_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usermalefolder_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usermalefolder_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_24m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_24m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weakfinancialgrowth_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weakfinancialgrowth_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property weekview_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("weekview_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
